### ISSUE TITLE
Empty keys

### ISSUE THREAD

**Issue by diedsmiling** [octet-stream/then-busboy#1]
Empty keys are parsed as empty strings. Is it intended to be so? Maybe they should be parsed into numeric indexes?

![postman 2016-10-12 20-57-58](https://cloud.githubusercontent.com/assets/1911142/19321689/af7534a6-90be-11e6-9c52-879133d71a4e.png)

**Comment by octet-stream** [comment]
Hello, thanks for the report!
I think it actually should throwing an error for empty top-level field names :)
