### ISSUE TITLE
File validation

### ISSUE THREAD

**Issue by diedsmiling** [octet-stream/then-busboy#16]
I've thought that a mime-type validation will be a nice feature to have here. For example, we can pass an option with the array of mime-types/mime-type patterns and only files with matched mime-types would be allowed. What do you think about it?

**Comment by octet-stream** [comment]
Hello :)
Sounds good. I'll add this feature as soon as I can :)

**Comment by octet-stream** [comment]
Hello again!
Sorry for a long time awaiting.
This feature has already added in 1.4.0 release :)

**Comment by diedsmiling** [comment]
Thanks!
