### ISSUE TITLE
mimeType of Fields

### ISSUE THREAD

**Issue by bill-kidwell** [octet-stream/then-busboy#18]
I'd like the ability to check the mimeType of a field.  This is possible with a change to onField.  To make this generic, I could generate an object with all of the information passed to onField.

In order to support backward compatibility, this would require an option of some sort.  

If there is already a way to override onField, that would work with no modifications, but I didn't see any.

**Comment by octet-stream** [comment]
Hello and thanks for your feedback!
I don't understand how (and why) do you want to get a mime-type information of a `field`. This kind of data represents only scalar types, such as `string`, `number` and so on. May be you need to get mime-type from `onFile`?
If so, I can add mime-type validation as it was in 1.x versions.

Or, if it is exactly what do you mean, could you explain me a use case for that?

**Comment by bill-kidwell** [comment]
Yeah, good question.  In our case we have an API gateway that receives and forwards a request.  Part of the information necessary to validate the request is also necessary to fulfill it.  To avoid looking up this information in both the gateway and the service (when possible) we generate a multi-part request with the original request and the additional information.

We could make these files, instead of fields, but fields also allow the mime type to be set in the client, so I'd like to be able to get to that information (in general, the string is either JSON or XML).  

After looking at the software a little closer, my thought was to add a Field class with value, enc, and mime.  Add an option for emitFieldObject which defaults to false.  This will provide the default behavior.  When set to true, The Field object would be placed in the fields object, rather than just the value.

**Comment by octet-stream** [comment]
So, you seems to need a full control over data processing, right? May be I can do this. Just need to figure out how it could be implemented and integrated with existent API. How urgent is this feature? I can look at this only on weekend. If you need this feature asap, maybe you would prefer to use [co-busboy](https://github.com/cojs/busboy) while I'm working on the solution.

**Comment by bill-kidwell** [comment]
Yes, having full control would work.
We have a workaround in place for now that works for us, so it is not urgent.
I checked the RFC on multi-part, and it is completely valid to specify the mimeType and transferEncoding there, which is why busboy provides it, but it does seem to be rare that it is used.  

Let me know if I can provide an example (e.g. a test case) that would help.  I can also take a first stab at adding a Field type and an option to return either the value, or the Field object, if you like that approach.

**Comment by octet-stream** [comment]
Yeah, it would be really helpful if you provide me a test case. I have some ideas, but just need an example to make sure I understand you correctly. Also, could you give me a link to that RFC's section about the use case you're talking about?

Speaking of public API: For know I think that then-busboy function might be re-implemented as thenable class with some additional methods to allow a full control over data processing. Each method will be executed with the same parameters given by `field` event (now I'm using only two of them as you can see). The class will be allowed execute without `new` (using [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy))

**Comment by bill-kidwell** [comment]
Sounds good, I will get you a documented use case, write some tests for it, and provide that reference.  I will knock that out over the weekend.

It does sound like the thenable-class implementation would give me access to the fields I need, so I am happy to try that out.  Just let me know.

Thanks,

Bill

**Comment by octet-stream** [comment]
I have added the first implementation of thenable class [here](https://github.com/octet-stream/then-busboy/blob/da403bbad067fa5a1b8e184f9aeedf5f00790a85/src/lib/ThenBusboy.mjs).

Just thoughts: It already works fine, but now we have inconsistent errors reporting, because some of them throws from constructor and some from `Promise` returned by `.exec()` method. then-busboy used only `Promise` for that before. Maybe I should move options and request validation back to the `.exec()` method.

Now I'm only waiting for test case from you.
I guess we need to discuss which additional methods do we need and when we will execute them:
  1. while busboy emits fields and files
  2. or before then-busboy returns an object created from fields and files.

**Comment by bill-kidwell** [comment]
*RE: The RFC*.  I was referring to this RFC
https://tools.ietf.org/html/rfc7578

The RFC does not seem to differentiate between a *File *or a *Field*,
although most libraries do.  This is true for each part.

In section 4.2, the RFC states (bolding mine):

   For form data that represents the content of a file, a name for the
   file SHOULD be supplied as well, by using a "filename" parameter of
   the Content-Disposition header field.  *The file name isn't mandatory
   for cases where the file name isn't available or is meaningless or
   private*; this might result, for example, when selection or drag-and-
   drop is used or when the form data content is streamed directly from
   a device.


Based on this, if I want to send file-like information (a JSON or XML
document), it is perfectly valid to send it without a filename.
In that case, it is emitted as a field, and the mimetype is not available.

4.4 <https://tools.ietf.org/html/rfc7578#section-4.4>. Content-Type Header
Field for Each Part

   Each part MAY have an (optional) "Content-Type" header field, which
   defaults to "text/plain".  If the contents of a file are to be sent,
   the file data SHOULD be labeled with an appropriate media type, if
   known, or "application/octet-stream".

**Comment by bill-kidwell** [comment]
Here is a gist that shows how I am using the functionality today.
https://gist.github.com/bill-kidwell/e015e1a8d9e968765a9aee9487fdcfa2 

You can see here where we assume that a part is JSON if it is a field, because we don't have the mime type.

Tests would include a multipart request with multiple JSON parts, then one with multiple XML parts, a mixture, and then verifying that our validation of the parts works (outside the scope of then-busboy).

I agree with your statement about moving things to exec for consistency of error handling.  I will take a look and see if I can use the thenable class to make this happen and share my results.

**Comment by octet-stream** [comment]
Hello again! Sorry for a long inactivity. :)

I guess I found another solution for that case.
In short, instead of attaching tasks to thenable `ThenBusboy` class a decided to add `Body` object returned by then busboy.
So, the future API will look like
```ts
declare function thenBusboy(request: http.IncomingMessage, options?: ThenBusboyOptions = {}): Promise<Body>
```

Where `Body` is a class represents entries produced by thenBusboy function + some helpers to transform it into JS object (use `Body#json()` method for that) or another FormData (use `Body#formData()` method for that). It also gives you an access to all entries using `Body#entries`, `Body#fields` or `Body#files`, plus you can produce new Body object because it will be a part of public API.

Oh, and of course I have added anther information to fields, so you can now check mime-type of each field :)
Hope it will helpful.

And I'm planning to release it as next major version because of breaking changes in public API. But I need to finish tests first and get a feedback from you :)

**Comment by bill-kidwell** [comment]
I will take a look.

Thanks,

Bill

**Comment by bill-kidwell** [comment]
I tried this out in our code and this seems to work well for our case.  Thanks for the help.

Will this be published to npm once you increment the version?  We will need it there in order to use it.

**Comment by octet-stream** [comment]
Glad to hear that.
Sure. It will be released as next major version in NPM when I'll finish all tests for Body class and utilities.
I'm planning this release on current (or next) weekend.

Do not close this issue for now, please.

**Comment by octet-stream** [comment]
It's done!
Now you can update then-busboy to 4.0.0 version from NPM registry.

I also added some more methods that helps to work with the data produced by then-busboy.
Check out [release note](https://github.com/octet-stream/then-busboy/releases/tag/4.0.0) and documentation for mode info.

**Comment by bill-kidwell** [comment]
Awesome. Thanks.
